### PR TITLE
Episode 32

### PR DESCRIPTION
**Pull request by benjaminreid**
Files are on there way up. Do you thing when you can, I've set the date for tomorrow, so no panic. :smile:

### CODE REVIEW

**Comment by daviddarnes** [comment]
Notes for me:
- GreenSock
- VR
- Star Wars

**Comment by daviddarnes** [comment]
@nouveller notes added, you think they are sufficient?

**Comment by benjaminreid** [comment]
@daviddarnes Yes! Shall we just duplicate the excerpt from the first line?

**Comment by daviddarnes** [comment]
@nouveller I added one :smile:

**Comment by benjaminreid** [comment]
Sweet! Shall be :rocket: ?

**Comment by daviddarnes** [comment]
:ship:

**Pull request merged**
