### PR TITLE
Episode #17

### PR DESCRIPTION
**Pull request by benjaminreid**
Adds a new variable for the Soundcloud URL and makes that and the audio file conditional.

### CODE REVIEW

**Comment by benjaminreid** [comment]
screen shot 2014-12-11 at 13 56 53

**Comment by benjaminreid** [comment]
@daviddarnes :eyes:

**Comment by daviddarnes** [comment]
Are we backdating these? Or leaving them for now?

**Comment by benjaminreid** [comment]
I think we’ll we’ll these are they are for now, but then back date them.

—
Benjamin Reid

**Pull request merged**
