### PR TITLE
Episode 31

### PR DESCRIPTION
**Pull request by benjaminreid**
This adds episode 31.

### CODE REVIEW

**Comment by benjaminreid** [comment]
@daviddarnes If you can fill in some details when you get a sec, that'd be lovely!

**Comment by daviddarnes** [comment]
@nouveller I've added notes, but was that everything?

**Comment by benjaminreid** [comment]
@daviddarnes Sounds good! Lets merge! :rocket:

**Comment by daviddarnes** [comment]
tumblr_ngfhvu9coa1r72ht7o1_500

**Pull request merged**
