### PR TITLE
v3.0

### PR DESCRIPTION
**Pull request by benjaminreid**
This implements our new design 🎉

### CODE REVIEW

**Comment by benjaminreid** [comment]
@daviddarnes This may suffice for now, RE the conflict. Can we just delete `_bitpodcast.scss`?

**Comment by daviddarnes** [comment]
@nouveller I _think_ you can but I can't be sure as it's still being imported. I'm guessing it's just a legacy file

**Comment by benjaminreid** [comment]
@daviddarnes Merged fixed, happy to ship?

**Comment by daviddarnes** [comment]
p2sdfkdazwigmabfmrzr

**Pull request merged**
