### PR TITLE
Episode 22

### PR DESCRIPTION
**Pull request by benjaminreid**

### CODE REVIEW

**Comment by benjaminreid** [comment]
@daviddarnes :eyes: 

Just uploading the mp3

**Comment by daviddarnes** [comment]
@nouveller notes are all here, advise hitting the edit button on the comment and copying out the markdown code https://github.com/nouveller/bitpodcast.com/issues/27

**Comment by daviddarnes** [comment]
Nice, was about to do it myself! Forgot about magic GitHub editing :sparkles:

**Comment by benjaminreid** [comment]
@daviddarnes Done, reckon we are good to go? Files are live!

**Comment by daviddarnes** [comment]
:shipit:

**Pull request merged**
