### PR TITLE
Episode 49

### PR DESCRIPTION
**Pull request by benjaminreid**

### CODE REVIEW

**Comment by benjaminreid** [comment]
Audio is ready!

**Comment by benjaminreid** [comment]
@daviddarnes Mind throwing some notes together when you get chance please!

**Comment by daviddarnes** [comment]
Sure! Sorry @nouveller, thanks for the nudge 😄

**Comment by daviddarnes** [comment]
@nouveller done :shipit:

**Comment by benjaminreid** [comment]
@daviddarnes That was quick! Thank-you!

**Pull request merged**
