### PR TITLE
Episode 24

### PR DESCRIPTION
**Pull request by benjaminreid**

### CODE REVIEW

**Comment by benjaminreid** [comment]
Here's the screenshot.

screen shot 2015-04-22 at 22 35 28

**Comment by daviddarnes** [comment]
@nouveller Added the content if you'd like to check it. Also added the episode length and put your image into a content directory within images, thought it'd be better to link to the image rather than putting it into the content so the page isn't too long.

**Comment by benjaminreid** [comment]
@daviddarnes Looks good to me, shall we :rocket:?

**Comment by daviddarnes** [comment]
@nouveller you're clear for launch :shipit:

**Pull request merged**
