### PR TITLE
[WIP] Episode 52

### PR DESCRIPTION
**Pull request by benjaminreid**
- [x] Link to youtube/embed
- [x] Audio files uploaded
- [x] Feature image?

### CODE REVIEW

**Comment by daviddarnes** [comment]
vicecity
Check out those polygons…

**Comment by daviddarnes** [comment]
:shipit:…

**Comment by daviddarnes** [comment]
https://bitpodcast.com/2017/01/26/episode-52/

**Comment by benjaminreid** [comment]
Man, that was fast! Top work sir.

**Pull request merged**
